name: S3 Deployment
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./checkout-cart
    
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm install
      working-directory: ${{ env.working-directory }}
    - name: Staging Build
      run: |
        npm build
      working-directory: ${{ env.working-directory }}
    - name: I
      uses: chrislennon/action-aws-cli@v1.1
    - name: Deployment
      # All commands after this point have access to the AWS CLI
      run: npm deploy
      env:
        AWS_S3_BUCKET: 'csc301a1'
        AWS_ACCESS_KEY_ID: 'AKIAYQ5HZXTK47HUW2UF'
        AWS_SECRET_ACCESS_KEY: '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'
        AWS_REGION: 'ca-central-1'
