name: S3 Deployment
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      
    - name: Install and Build
      run:
        cd checkout-cart &&
        npm install &&
        npm build &&
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "./awscliv2.zip"
    
    - name: Install aws-cli
      run: |
        cd checkout-cart &&
        sudo apt-get install -y unzip &&
        unzip "./awscliv2.zip" &&
        chmod +x ./aws/install &&
        sudo ./aws/install
